### ISSUE TITLE
Arduino Library format is incorrect, zip import also does not work

### ISSUE THREAD

**Issue by JesseCake** [Solo-FL/SOLO-motor-controllers-ARDUINO-library#11]
Hi there,

It appears the format of this Arduino library needs some formatting in order to work well with the Arduino IDE.

Following your direct instructions to install via the "include library->zip" method results in errors. It appears as if the format of the folder is not standard Arduino library formatting.

Usually you'll see files like:
keywords.txt
library.properties

etc in the sub folder.

Making the installation process smooth will help new users adopt your motor controller into their projects.

Many thanks

**Comment by Solo-FL** [comment]
Thank for your suggestion we will move to make it batter

**Comment by Solo-FL** [comment]
@JesseCake we update the library to work with the standard Arduino IDE library manager.
