### ISSUE TITLE
`ResetPositionToZero()` does not work?

### ISSUE THREAD

**Issue by Saad-Mufti** [Solo-FL/SOLO-motor-controllers-ARDUINO-library#12]
I'm trying to initialize a motor I have connected to a SoloUNO Mini_V2, starting with setting the modes and then resetting the encoder position to 0 with `ResetPositionToZero()`, like so:

```
    SOLOMotorControllersUart solo_driver4 = SOLOMotorControllersUart((unsigned char)0, Serial2, SOLOMotorControllers::UartBaudrate::rate937500, 200L, 5);

  solo_driver4.SetFeedbackControlMode(SOLOMotorControllers::FeedbackControlMode::encoders);
  solo_driver4.SetControlMode(SOLOMotorControllers::ControlMode::positionMode);
  solo_driver4.SetPositionControllerKp(0.0195693);
  solo_driver4.SetPositionControllerKi(0);
  solo_driver4.ResetPositionToZero();
```

However, in my Serial Monitor, I find that on startup, calling `GetPositionCountsFeedback()` returns a non-zero value. I am not setting a target position. Any idea what I might be doing wrong?

**Comment by Solo-FL** [comment]
ResetPositionToZero is under firmware development, in the future version will be operational.
Today's alternative is: 
1) during initialization: store the starting position 
2) during the position change: send your position + the starting position

```
\\1 initialize
offset = solo_driver4.GetPositionCountsFeedback();

\\2 during runtime
 solo_driver4.SetPositionReference(offset+myPosition);
```
