### ISSUE TITLE
Conversion of float to data bug

### ISSUE THREAD

**Issue by l4m4re** [Solo-FL/SOLO-motor-controllers-ARDUINO-library#8]
Conversion of float to/from data goes wrong, probably by the conversion from data to float.  It is often offset by 0.5.

Replication, see the following program:

-:-

#include <SOLOMotorController.h>
 
//instanciate a SOLO object:
SOLOMotorController *SOLO_Obj1; 

//the device address of SOLO:
unsigned char SOLO_address1=0; 

void setup() {
  Serial.begin(115200); 

  //Initialize the SOLO object
  SOLO_Obj1 = new SOLOMotorController(SOLO_address1); 
  delay(2000);

  unsigned char data[4];
  float f2;
  long ld;
  for( float f=-0.1; f<0.5; f+=0.01)
  {  
    SOLO_Obj1->ConvertToData(f,data);
    f2 = SOLO_Obj1->ConvertToFloat( data );
    ld = SOLO_Obj1->ConvertToLong( data );
    Serial.print(f , 7);
    Serial.print(", ");
    Serial.print(f2 , 7);
    Serial.print(", ");
    Serial.println(ld);
       
  }
}

void loop() {}

-:-

Program output:

-0.1000000, -0.6000061, 4294888652
-0.0900000, -0.5900040, 4294889963
-0.0800000, -0.5800018, 4294891274
-0.0700000, -0.5700073, 4294892584
-0.0600000, -0.5600052, 4294893895
-0.0500000, -0.5500030, 4294895206
-0.0400000, -0.5400009, 4294896517
-0.0300000, -0.5300064, 4294897827
-0.0200000, -0.5200043, 4294899138
-0.0100000, -0.5100021, 4294900449
-0.0000000, 0.0000000, 0
0.0100000, 0.0099945, 1310
0.0200000, 0.0199966, 2621
0.0300000, 0.0299988, 3932
0.0400000, 0.0399933, 5242
0.0500000, 0.0499954, 6553
0.0600000, 0.0599976, 7864
0.0700000, 0.0699997, 9175
0.0800000, 0.0799942, 10485
0.0900000, 0.0899963, 11796
0.1000000, 0.0999985, 13107
0.1100000, 0.1099930, 14417
0.1200000, 0.1199951, 15728
0.1300000, 0.1299973, 17039
0.1400000, 0.1399994, 18350
0.1500000, 0.1499939, 19660
0.1600000, 0.1599960, 20971
0.1700000, 0.1699982, 22282
0.1800000, 0.1799927, 23592
0.1900000, 0.1899948, 24903
0.2000000, 0.1999969, 26214
0.2100000, 0.2099991, 27525
0.2200000, 0.2199936, 28835
0.2300000, 0.2299957, 30146
0.2400000, 0.2399979, 31457
0.2500000, -0.2500000, 4294934528
0.2600000, -0.2400055, 4294935838
0.2700000, -0.2300034, 4294937149
0.2800000, -0.2200012, 4294938460
0.2900000, -0.2100067, 4294939770
0.3000000, -0.2000046, 4294941081
0.3100000, -0.1900024, 4294942392
0.3200000, -0.1800003, 4294943703
0.3300000, -0.1700058, 4294945013
0.3400000, -0.1600037, 4294946324
0.3500000, -0.1500015, 4294947635
0.3599999, -0.1400070, 4294948945
0.3699999, -0.1300049, 4294950256
0.3799999, -0.1200027, 4294951567
0.3899999, -0.1100006, 4294952878
0.3999999, -0.1000061, 4294954188
0.4099999, -0.0900040, 4294955499
0.4199999, -0.0800018, 4294956810
0.4299999, -0.0700073, 4294958120
0.4399999, -0.0600052, 4294959431
0.4499999, -0.0500030, 4294960742
0.4599998, -0.0400009, 4294962053
0.4699998, -0.0300064, 4294963363
0.4799998, -0.0200043, 4294964674
0.4899998, -0.0100021, 4294965985
0.4999998, -0.0000076, 4294967295

**Comment by l4m4re** [comment]
Found the solution on the forum. Same bug also in ConvertToLong method.

https://www.solomotorcontrollers.com/forum/postid/683/

**Comment by Solo-FL** [comment]
We push the fix over conversion.
Thank you.

15:22:38.093 -> -0.1000000, -0.1000061, -13108
15:22:38.140 -> -0.0900000, -0.0900040, -11797
15:22:38.140 -> -0.0800000, -0.0800018, -10486
15:22:38.140 -> -0.0700000, -0.0700073, -9176
15:22:38.140 -> -0.0600000, -0.0600052, -7865
15:22:38.140 -> -0.0500000, -0.0500030, -6554
15:22:38.140 -> -0.0400000, -0.0400009, -5243
15:22:38.140 -> -0.0300000, -0.0300064, -3933
15:22:38.140 -> -0.0200000, -0.0200043, -2622
15:22:38.140 -> -0.0100000, -0.0100021, -1311
15:22:38.140 -> -0.0000000, 0.0000000, 0
15:22:38.140 -> 0.0100000, 0.0099945, 1310
15:22:38.140 -> 0.0200000, 0.0199966, 2621
15:22:38.140 -> 0.0300000, 0.0299988, 3932
15:22:38.140 -> 0.0400000, 0.0399933, 5242
15:22:38.140 -> 0.0500000, 0.0499954, 6553
15:22:38.140 -> 0.0600000, 0.0599976, 7864
15:22:38.140 -> 0.0700000, 0.0699997, 9175
15:22:38.186 -> 0.0800000, 0.0799942, 10485
15:22:38.186 -> 0.0900000, 0.0899963, 11796
15:22:38.186 -> 0.1000000, 0.0999985, 13107
15:22:38.186 -> 0.1100000, 0.1099930, 14417
15:22:38.186 -> 0.1200000, 0.1199951, 15728
15:22:38.186 -> 0.1300000, 0.1299973, 17039
15:22:38.186 -> 0.1400000, 0.1399994, 18350
15:22:38.186 -> 0.1500000, 0.1499939, 19660
15:22:38.186 -> 0.1600000, 0.1599960, 20971
15:22:38.186 -> 0.1700000, 0.1699982, 22282
15:22:38.186 -> 0.1800000, 0.1799927, 23592
15:22:38.186 -> 0.1900000, 0.1899948, 24903
15:22:38.186 -> 0.2000000, 0.1999969, 26214
15:22:38.186 -> 0.2100000, 0.2099991, 27525
15:22:38.186 -> 0.2200000, 0.2199936, 28835
15:22:38.186 -> 0.2300000, 0.2299957, 30146
15:22:38.186 -> 0.2400000, 0.2399979, 31457
15:22:38.186 -> 0.2500000, 0.2500000, 32768
15:22:38.186 -> 0.2600000, 0.2599945, 34078
15:22:38.186 -> 0.2700000, 0.2699966, 35389
15:22:38.232 -> 0.2800000, 0.2799988, 36700
15:22:38.232 -> 0.2900000, 0.2899933, 38010
15:22:38.232 -> 0.3000000, 0.2999954, 39321
15:22:38.232 -> 0.3100000, 0.3099976, 40632
15:22:38.232 -> 0.3200000, 0.3199997, 41943
15:22:38.232 -> 0.3300000, 0.3299942, 43253
15:22:38.232 -> 0.3400000, 0.3399963, 44564
15:22:38.232 -> 0.3500000, 0.3499985, 45875
15:22:38.232 -> 0.3599999, 0.3599930, 47185
15:22:38.232 -> 0.3699999, 0.3699951, 48496
15:22:38.232 -> 0.3799999, 0.3799973, 49807
15:22:38.232 -> 0.3899999, 0.3899994, 51118
15:22:38.232 -> 0.3999999, 0.3999939, 52428
15:22:38.232 -> 0.4099999, 0.4099960, 53739
15:22:38.232 -> 0.4199999, 0.4199982, 55050
15:22:38.232 -> 0.4299999, 0.4299927, 56360
15:22:38.232 -> 0.4399999, 0.4399948, 57671
15:22:38.232 -> 0.4499999, 0.4499969, 58982
15:22:38.232 -> 0.4599998, 0.4599991, 60293
15:22:38.280 -> 0.4699998, 0.4699936, 61603
15:22:38.280 -> 0.4799998, 0.4799957, 62914
15:22:38.280 -> 0.4899998, 0.4899979, 64225
15:22:38.280 -> 0.4999998, 0.4999924, 65535
